#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 23 11:08:19 2020

@author: marleezinsser
"""

# This script gives the number of nodes and the number of relationships that 
#should be expected in the neo4j db after its initial upload.

import csv
import pandas as pd
df = pd.read_csv('/Users/marleezinsser/opt/anaconda3/lib/python3.7/site-packages/neo4j/import/PMID-MESH-DISEASE.csv')
num_PMID_nodes = df['PMID'].nunique()
num_MESH_nodes = df['MESH'].nunique()
num_Disease_nodes = df['Disease'].nunique()

total_nodes = num_PMID_nodes + num_MESH_nodes + num_Disease_nodes

#Each row represents 2 relationships
total_relationships = (len(df.index) ) *2
