#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar  5 13:23:44 2020

@author: marleezinsser
"""

import pandas as pd
df = pd.read_csv('/Users/marleezinsser/Desktop/arrhythmia-similar-diseases.csv')


sim_diseases = df['Name']
sim_diseases = sim_diseases.dropna()


df_new = pd.DataFrame(columns = ['target_disease', 'sim_diseases'])
df_new['sim_diseases']=sim_diseases
df_new['target_disease']='arrhythmia'

